name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate GitHub profile summary cards

    steps:
      - name: Checkout repository with profile token
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PROFILE_SUMMARY_TOKEN }}
          ref: main

      - name: Generate profile summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_SUMMARY_TOKEN }}
        with:
          USERNAME: andreclerigo
          BRANCH_NAME: main
          UTC_OFFSET: 0
          EXCLUDE: "mect_2ano,msc-thesis-template"
          AUTO_PUSH: true
